def get_states():
    states ={
        'Rajasthan' : ['Rajasthan', 
                    'Ajmer',
                    'Alwar',
                    'Banswara',
                    'Baran',
                    'Barmer',
                    'Bharatpur',
                    'Bhilwara',
                    'Bikaner',
                    'Bundi',
                    'Chittorgarh',
                    'Churu',
                    'Dausa',
                    'Dholpur',
                    'Dungarpur',
                    'Hanumangarh',
                    'Jaipur',
                    'Jaisalmer',
                    'Jalore',
                    'Jhalawar',
                    'Jhunjhunu',
                    'Jodhpur',
                    'Karauli',
                    'Kota',
                    'Nagaur',
                    'Pali',
                    'Pratapgarh',
                    'Rajsamand',
                   ' Sawai Madhopur',
                   ' Sikar',
                   ' Sirohi',
                    'Sri Ganganagar',
                    'Tonk',
                   ' Udaipur'],

        'Maharashtra' :['Maharashtra',
                    'Ahmednagar',
                    'Akola',
                    'Amravati',
                    'Aurangabad',
                    'Beed',
                    'Bhandara',
                    'Buldhana',
                    'Chandrapur',
                    'Dhule',
                    'Gadchiroli',
                    'Gondia',
                    'Hingoli',
                    'Jalgaon',
                    'Jalna',
                    'Kolhapur',
                    'Latur',
                    'Mumbai City',
                    'Mumbai Suburban',
                    'Nagpur',
                    'Nanded',
                    'Nandurbar',
                    'Nashik',
                    'Osmanabad',
                    'Palghar',
                    'Parbhani',
                    'Pune',
                    'Raigad',
                    'Ratnagiri',
                    'Sangli',
                    'Satara',
                    'Sindhudurg',
                    'Solapur',
                    'Thane',
                    'Wardha',
                    'Washim',
                    'Yavatmal',],
    
        "Karnataka" : ["Karnataka",
                    'Bagalkot',
                    'Ballari',
                    'Belagavi',
                    'Bengaluru',
                    'Bidar',
                    'Chamarajanagar',
                    'Chikballapur',
                    'Chikkamagaluru',
                    'Chitradurga',
                    'Dakshina Kannada',
                    'Davangere',
                    'Dharwad',
                    'Gadag',
                    'Hassan',
                    'Haveri',
                    'Kalaburagi',
                    'Kodagu',
                    'Kolar',
                    'Koppal',
                    'Mandya',
                    'Mysuru',
                    'Raichur',
                    'Ramanagara',
                    'Shivamogga',
                    'Tumakuru',
                    'Udupi',
                    'Uttara Kannada',
                    'Vijayapura',
                    'Yadgir',],

        'Delhi ':     ['Delhi ',
                    'Central Delhi',
                    'East Delhi',
                    'New Delhi',
                    'North Delhi',
                    'North East Delhi',
                    'North West Delhi',
                    'Shahdara',
                    'South Delhi',
                    'South East Delhi',
                    'South West Delhi',
                    'West Delhi',] ,
    
        'Haryana':     ['Haryana',
                    'Ambala',
                    'Bhiwani',
                    'Charkhi Dadri',
                    'Faridabad',
                    'Fatehabad',
                    'Gurugram',
                    'Hisar',
                    'Jhajjar',
                    'Jind',
                    'Kaithal',
                    'Karnal',
                    'Kurukshetra',
                    'Mahendragarh',
                    'Nuh',
                    'Palwal',
                    'Panchkula',
                    'Panipat',
                    'Rewari',
                    'Rohtak',
                    'Sirsa',
                    'Sonipat',
                    'Yamunanagar',],

        'Himachal Pradesh': ['Himachal Pradesh',
                        'Bilaspur',
                        'Chamba',
                        'Hamirpur',
                        'Kangra',
                        'Kinnaur',
                        'Kullu',
                        'Lahaul & Spiti',
                        'Mandi',
                        'Shimla',
                        'Sirmaur',
                        'Solan',
                        'Una',],

        'JK' : [        'Jk',    
                        'Jammu & Kashmir',
                        'Anantnag',
                        'Bandipore',
                        'Baramulla',
                        'Budgam',
                        'Doda',
                        'Ganderbal',
                        'Jammu',
                        'Kathua',
                        'Kishtwar',
                        'Kulgam',
                        'Kupwara',
                        'Poonch',
                        'Pulwama',
                        'Rajouri',
                        'Ramban',
                        'Reasi',
                        'Samba',
                        'Shopian',
                        'Srinagar',
                        'Udhampur',],
    
        'Jharkhand' : ['Jharkhand',
                    'Bokaro',
                    'Chatra',
                    'Deoghar',
                    'Dhanbad',
                    'Dumka',
                    'East Singhbhum',
                    'Garhwa',
                    'Giridih',
                    'Godda',
                    'Gumla',
                    'Hazaribag',
                    'Jamtara',
                    'Khunti',
                    'Koderma',
                    'Latehar',
                    'Lohardaga',
                    'Pakur',
                    'Palamu',
                    'Ramgarh',
                    'Ranchi',
                    'Sahibganj',
                    'Seraikela-Kharsawan',
                    'Simdega',
                    'West Singhbhum',],

        'Gujarat' : ['Gujarat',
                'Ahmedabad',
                'Amreli',
                'Anand',
                'Aravalli',
                'Banaskantha',
                'Bharuch',
                'Bhavnagar',
                'Botad',
                'Chhota Udepur',
                'Dahod',
                'Dangs',
                'Devbhoomi Dwarka',
                'Gandhinagar',
                'Gir Somnath',
                'Jamnagar',
                'Junagadh',
                'Kachchh',
                'Kheda',
                'Mahisagar',
                'Mehsana',
                'Morbi',
                'Narmada',
                'Navsari',
                'Panchmahal',
                'Patan',
                'Porbandar',
                'Rajkot',
                'Sabarkantha',
                'Surat',
                'Surendranagar',
                'Tapi',
                'Vadodara',
                'Valsad',],
    
        'Andhra Pradesh' : ['Andhra Pradesh',
                        'Anantapur',
                        'Chittoor',
                        'East Godavari',
                        'Guntur',
                        'Krishna',
                        'Kurnool',
                        'Prakasam',
                        'Srikakulam',
                        'Sri Potti Sriramulu Nellore',
                        'Visakhapatnam',
                        'Vizianagaram',
                        'West Godavari',
                        'Kadapa',],

        'Arunachal Pradesh':['Arunachal Pradesh',
                        'Anjaw',
                        'Changlang',
                        'Dibang Valley',
                        'East Kameng',
                        'East Siang',
                        'Kamle',
                        'Kra Daadi',
                        'Kurung Kumey',
                        'Lepa Rada',
                        'Lohit',
                        'Longding',
                        'Lower Dibang Valley',
                        'Lower Siang',
                        'Lower Subansiri',
                        'Namsai',
                        'Pakke Kessang',
                        'Papum Pare',
                        'Shi Yomi',
                        'Siang',
                        'Tawang',
                        'Tirap',
                        'Upper Siang',
                        'Upper Subansiri',
                        'West Kameng',
                        'West Siang',],

        'Assam' : ['Assam',
                'Baksa',
                'Barpeta',
                'Biswanath',
                'Bongaigaon',
                'Cachar',
                'Charaideo',
                'Chirang',
                'Darrang',
                'Dhemaji',
                'Dhubri',
                'Dibrugarh',
                'Dima Hasao',
                'Goalpara',
                'Golaghat',
                'Hailakandi',
                'Hojai',
                'Jorhat',
                'Kamrup',
                'Kamrup Metropolitan',
                'Karbi Anglong',
                'Karimganj',
                'Kokrajhar',
                'Lakhimpur',
                'Majuli',
                'Morigaon',
                'Nagaon',
                'Nalbari',
                'Sivasagar',
                'Sonitpur',
                'South Salamara-Mankachar',
                'Tinsukia',
                'Udalguri',
                'West Karbi Anglong',],

        'Bihar' : ['Bihar',
                'Araria',
                'Arwal',
                'Aurangabad',
                'Banka',
                'Begusarai',
                'Bhagalpur',
                'Bhojpur',
                'Buxar',
                'Darbhanga',
                'East Champaran',
                'Gaya',
                'Gopalganj',
                'Jamui',
                'Jehanabad',
                'Kaimur',
                'Katihar',
                'Khagaria',
                'Kishanganj',
                'Lakhisarai',
                'Madhepura',
                'Madhubani',
                'Munger',
                'Muzaffarpur',
                'Nalanda',
                'Nawada',
                'Patna',
                'Purnia',
                'Rohtas',
                'Saharsa',
                'Samastipur',
                'Saran',
                'Sheikhpura',
                'Sheohar',
                'Sitamarhi',
                'Siwan',
                'Supaul',
                'Vaishali',
                'West Champaran',],

        'Chhattisgarh':['Chhattisgarh',
                    'Balod',
                    'Baloda Bazar',
                    'Balrampur',
                    'Bastar',
                    'Bemetara',
                    'Bijapur',
                    'Bilaspur',
                    'Dantewada',
                    'Dhamtari',
                    'Durg',
                    'Gariyaband',
                    'Janjgir-Champa',
                    'Jashpur',
                    'Kabirdham',
                    'Kanker',
                    'Kondagaon',
                    'Korba',
                    'Korea',
                    'Mahasamund',
                    'Mungeli',
                    'Narayanpur',
                    'Raigarh',
                    'Raipur',
                    'Rajnandgaon',
                    'Sukma',
                    'Surajpur',
                    'Surguja',],

        'Kerala':['Kerala',
                'Alappuzha',
                'Ernakulam',
                'Idukki',
                'Kannur',
                'Kasaragod',
                'Kollam',
                'Kottayam',
                'Kozhikode',
                'Malappuram',
                'Palakkad',
                'Pathanamthitta',
                'Thiruvananthapuram',
                'Thrissur',
                'Wayanad',],

        'Madhya Pradesh': ['Mp'
                        'Madhya Pradesh',
                        'Agar Malwa',
                        'Alirajpur',
                        'Anuppur',
                        'Ashoknagar',
                        'Balaghat',
                        'Barwani',
                        'Betul',
                        'Bhind',
                        'Bhopal',
                        'Burhanpur',
                        'Chhatarpur',
                        'Chhindwara',
                        'Damoh',
                        'Datia',
                        'Dewas',
                        'Dhar',
                        'Dindori',
                        'Guna',
                        'Gwalior',
                        'Harda',
                        'Hoshangabad',
                        'Indore',
                        'Jabalpur',
                        'Jhabua',
                        'Katni',
                        'Khandwa',
                        'Khargone',
                        'Mandla',
                        'Mandsaur',
                        'Morena',
                        'Narsinghpur',
                        'Neemuch',
                        'Panna',
                        'Raisen',
                        'Rajgarh',
                        'Ratlam',
                        'Rewa',
                        'Sagar',
                        'Satna',
                        'Sehore',
                        'Seoni',
                        'Shahdol',
                        'Shajapur',
                        'Sheopur',
                        'Shivpuri',
                        'Sidhi',
                        'Singrauli',
                        'Tikamgarh',
                        'Ujjain',
                        'Umaria',
                        'Vidisha',],

        'Manipur': ['Manipur',
                'Bishnupur',
                'Chandel',
                'Churachandpur',
                'Imphal East',
                'Imphal West',
                'Jiribam',
                'Kakching',
                'Kamjong',
                'Kangpokpi',
                'Noney',
                'Pherzawl',
                'Senapati',
                'Tamenglong',
                'Tengnoupal',
                'Thoubal',
                'Ukhrul',],


        'Meghalaya': ['Meghalaya',
                    'East Garo Hills',
                    'East Jaintia Hills',
                    'East Khasi Hills',
                    'North Garo Hills',
                    'Ri Bhoi',
                    'South Garo Hills',
                    'South West Garo Hills',
                    'South West Khasi Hills',
                    'West Garo Hills',
                    'West Jaintia Hills',
                    'West Khasi Hills',],

        'Odisha' : ['Odisha',
                'Angul',
                'Balangir',
                'Balasore',
                'Bargarh',
                'Bhadrak',
                'Boudh',
                'Cuttack',
                'Deogarh',
                'Dhenkanal',
                'Gajapati',
                'Ganjam',
                'Jagatsinghapur',
                'Jajpur',
                'Jharsuguda',
                'Kalahandi',
                'Kandhamal',
                'Kendrapara',
                'Kendujhar',
                'Khordha',
                'Koraput',
                'Malkangiri',
                'Mayurbhanj',
                'Nabarangpur',
                'Nayagarh',
                'Nuapada',
                'Puri',
                'Rayagada',
                'Sambalpur',
                'Sonepur',
                'Sundargarh',],

        'Punjab': ['Punjab',
                'Amritsar',
                'Barnala',
                'Bathinda',
                'Faridkot',
                'Fatehgarh Sahib',
                'Fazilka',
                'Ferozepur',
                'Gurdaspur',
                'Hoshiarpur',
                'Jalandhar',
                'Kapurthala',
                'Ludhiana',
                'Mansa',
                'Moga',
                'Muktsar',
                'Nawanshahr',
                'Pathankot',
                'Patiala',
                'Rupnagar',
                'Mohali',
                'Sangrur',
                'Tarn Taran',],

        'Tamil Nadu':['Tamil Nadu',
                    'Ariyalur',
                    'Chengalpattu',
                    'Chennai',
                    'Coimbatore',
                    'Cuddalore',
                    'Dharmapuri',
                    'Dindigul',
                    'Erode',
                    'Kallakurichi',
                    'Kanchipuram',
                    'Kanyakumari',
                    'Karur',
                    'Krishnagiri',
                    'Madurai',
                    'Nagapattinam',
                    'Namakkal',
                    'Nilgiris',
                    'Perambalur',
                    'Pudukkottai',
                    'Ramanathapuram',
                    'Ranipet',
                    'Salem',
                    'Sivaganga',
                    'Tenkasi',
                    'Thanjavur',
                    'Theni',
                    'Thoothukudi',
                    'Tiruchirappalli',
                    'Tirunelveli',
                    'Tirupathur',
                    'Tiruppur',
                    'Tiruvallur',
                    'Tiruvannamalai',
                    'Tiruvarur',
                    'Vellore',
                    'Viluppuram',
                    'Virudhunagar',],


        'Telangana': ['Telangana',
                    'Adilabad',
                    'Bhadradri Kothagudem',
                    'Hyderabad',
                    'Jagtial',
                    'Jangaon',
                    'Jayashankar Bhoopalpally',
                    'Jogulamba Gadwal',
                    'Kamareddy',
                    'Karimnagar',
                    'Khammam',
                    'Komaram Bheem Asifabad',
                    'Mahabubabad',
                    'Mahabubnagar',
                    'Mancherial',
                    'Medak',
                    'Medchal',
                    'Nagarkurnool',
                    'Nalgonda',
                    'Nirmal',
                    'Nizamabad',
                    'Peddapalli',
                    'Rajanna Sircilla',
                    'Rangareddy',
                    'Sangareddy',
                    'Siddipet',
                    'Suryapet',
                    'Vikarabad',
                    'Wanaparthy',
                    'Warangal',
                    'Yadadri Bhuvanagiri',],

        'Uttarakhand': ['Uk'
                    'Uttarakhand',
                    'Almora',
                    'Bageshwar',
                    'Chamoli',
                    'Champawat',
                    'Dehradun',
                    'Haridwar',
                    'Nainital',
                    'Pauri Garhwal',
                    'Pithoragarh',
                    'Rudraprayag',
                    'Tehri Garhwal',
                    'Udham Singh Nagar',
                    'Uttarkashi',],

        'Uttar Pradesh': ['Up'
                        'Uttar Pradesh',
                        'Agra',
                        'Aligarh',
                        'Allahabad',
                        'Ambedkar Nagar',
                        'Amethi',
                        'Amroha',
                        'Auraiya',
                        'Azamgarh',
                        'Baghpat',
                        'Bahraich',
                        'Ballia',
                        'Balrampur',
                        'Banda',
                        'Barabanki',
                        'Bareilly',
                        'Basti',
                        'Bhadohi',
                        'Bijnor',
                        'Budaun',
                        'Bulandshahr',
                        'Chandauli',
                        'Chitrakoot',
                        'Deoria',
                        'Etah',
                        'Etawah',
                        'Faizabad',
                        'Farrukhabad',
                        'Fatehpur',
                        'Firozabad',
                        'Gautam Buddha Nagar',
                        'Ghaziabad',
                        'Ghazipur',
                        'Gonda',
                        'Gorakhpur',
                        'Hamirpur',
                        'Hapur',
                        'Hardoi',
                        'Hathras',
                        'Jalaun',
                        'Jaunpur',
                        'Jhansi',
                        'Kannauj',
                        'Kanpur Dehat',
                        'Kanpur Nagar',
                        'Kanshiram Nagar',
                        'Kaushambi',
                        'Kushinagar',
                        'Lakhimpur - Kheri',
                        'Lalitpur',
                        'Lucknow',
                        'Maharajganj',
                        'Mahoba',
                        'Mainpuri',
                        'Mathura',
                        'Mau',
                        'Meerut',
                        'Mirzapur',
                        'Moradabad',
                        'Muzaffarnagar',
                        'Pilibhit',
                        'Pratapgarh',
                        'RaeBareli',
                        'Rampur',
                        'Saharanpur',
                        'Sambhal',
                        'Sant Kabir Nagar',
                        'Shahjahanpur',
                        'Shamali',
                        'Shravasti',
                        'Siddharth Nagar',
                        'Sitapur',
                        'Sonbhadra',
                        'Sultanpur',
                        'Unnao',
                        'Varanasi',]  ,
        'West Bengal': ['West Bengal',
                    'Wb'
                    'Alipurduar',
                    'Bankura',
                    'Birbhum',
                    'Cooch Behar',
                    'Dakshin Dinajpur',
                    'Darjeeling',
                    'Hooghly',
                    'Howrah',
                    'Jalpaiguri',
                    'Jhargram',
                    'Kalimpong',
                    'Kolkata',
                    'Malda',
                    'Murshidabad',
                    'Nadia',
                    'North 24 Parganas',
                    'Paschim Medinipur',
                    'Paschim (West) Burdwan',
                    'Purba Burdwan',
                    'Purba Medinipur',
                    'Purulia',
                    'South 24 Parganas',
                    'Uttar Dinajpur',]                
    }

    return states